name: Add Gradle Wrapper 8.7
on: workflow_dispatch

permissions:
  contents: write

jobs:
  gen:
    runs-on: windows-latest
    steps:
      - name: Checkout with GITHUB_TOKEN
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Remove old Gradle wrapper (if exists)
        run: |
          echo Cleaning up old Gradle wrapper...
          if exist gradlew del /f gradlew
          if exist gradlew.bat del /f gradlew.bat
          if exist gradle rmdir /s /q gradle
        shell: cmd

      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate new Gradle wrapper (8.7)
        run: gradle wrapper --gradle-version 8.7 --distribution-type all --stacktrace --info

      - name: Commit & push Gradle wrapper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f gradlew gradlew.bat gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties
          git commit -m "Update Gradle wrapper to 8.7" || exit 0
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push
