name: Build Android with Gradle Wrapper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Decode google-services.json
      - name: Restore google-services.json
        run: |
          mkdir -p app
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      # 4. Install Gradle CLI
      - name: Install Gradle CLI 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-disabled: true

      # 5. Find Gradle project root
      - name: Detect Gradle root
        id: findroot
        run: |
          echo "Looking for build.gradle..."
          ROOT=$(find . -maxdepth 3 -type f \( -name "build.gradle" -o -name "build.gradle.kts" \) -printf '%h\n' | head -n 1)
          echo "Found Gradle root: $ROOT"
          echo "root=$ROOT" >> $GITHUB_OUTPUT

      # 6. Generate Gradle wrapper in that root
      - name: Generate Gradle wrapper
        run: |
          cd "${{ steps.findroot.outputs.root }}"
          gradle wrapper --gradle-version 8.7 --distribution-type all --stacktrace --info --refresh-dependencies

      # 7. Commit wrapper back (optional)
      - name: Commit & push Gradle wrapper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f gradlew gradlew.bat gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties app/google-services.json
          git commit -m "Add Gradle wrapper 8.7" || echo "No changes"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push

      # 8. Build APK
      - name: Build Debug APK
        run: |
          cd "${{ steps.findroot.outputs.root }}"
          ./gradlew assembleDebug --stacktrace --info
