name: Add Gradle Wrapper 8.9
on: workflow_dispatch

permissions:
  contents: write

jobs:
  gen:
    runs-on: windows-latest
    steps:
      - name: Checkout with GITHUB_TOKEN
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate wrapper in root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gradle wrapper --gradle-version 8.9 --distribution-type all
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f gradlew gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties
          git commit -m "Add Gradle wrapper 8.9" || echo "No changes"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push
