name: Update Gradle Wrapper to 8.9

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update Gradle Wrapper
        run: |
          ./gradlew wrapper --gradle-version 8.9 --distribution-type all
          
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f gradlew gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties
          git commit -m "Update Gradle wrapper to 8.9" || echo "No changes"
          git push
